# This container defines an environment you can use to get started with pynusmv
# instantly (if ie there is no binary distribution available for your platform).
#
# This file is part of the pynusmv distribution. As such it is licensed to you
# under the term of the LGPLv2. For more information regarding the legal aspect
# of this licensing, please refer to the full text of the license on the free
# software foundation website.
#
# Author: X. Gillard <xavier.gillard [at] uclouvain.be>
FROM python

MAINTAINER Xavier Gillard <xavier.gillard@uclouvain.be>

# Just for the convenience of it
RUN pip3 install pynusmv

CMD python3
